name: Test

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
          logout: false
      -
        name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v1
      -
        name: Build and push
        id: docker_build_spa
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          outputs: type=oci,dest=/tmp/image.tar
          tags: eu.gcr.io/yslow1/debug1:latest
          target: stage1
      - 
        name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          sudo: true
