name: Test

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get version
        id: getv
        run: |
          echo GITHUB_SHA $GITHUB_SHA
          echo GITHUB_REF $GITHUB_REF
          npm run env | grep npm_package_version >> $GITHUB_ENV
          echo GITHUB_SHA_SHORT=`git rev-parse --short HEAD` >> $GITHUB_ENV

      - name: test vars
        run: |
          echo GITHUB_SHA_SHORT $GITHUB_SHA_SHORT
          echo npm_package_version $npm_package_version
    
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          target: frontend
          build_args: code_version=${{ env.npm_package_version }}-${{ env.GITHUB_SHA_SHORT }}
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
          repository: debug1/spa-server
          tags: staging,${{ jobs. }}
          tag_with_ref: true
          tag_with_sha: true