name: Test

on:
  release:
    types: [published, updated]

env:
  PROJECT_ID: yslow1
  GKE_CLUSTER: debug1
  GKE_ZONE: europe-west2-c    

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: get version
        id: getv
        run: |
          echo GITHUB_SHA $GITHUB_SHA
          echo GITHUB_REF $GITHUB_REF

      - name: get version
        id: getv1
        run: |
          echo image_tag=sha-$(GITHUB_SHA:0:7) >> $GITHUB_ENV

      - name: Setup gcloud command
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_JSON_KEY }}
          project_id: ${{ env.PROJECT_ID }}
  
      # Setup kubectl with credentials to access the cluster
      - name: Setup kubectl
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
  
      # Tag the release as production in the container registry
      - name: Tag images
        run: |-
          gcloud container images add-tag \
          eu.gcr.io/yslow1/spa-server:${{ env.image_tag}} \
          eu.gcr.io/yslow1/spa-server:production
          
          gcloud container images add-tag \
          eu.gcr.io/yslow1/api-server:${{ env.image_tag}} \
          eu.gcr.io/yslow1/api-server:production
  
      - name: Deploy to Production
        run: |-
          echo Deploying release $GITHUB_REF to production
          kubectl rollout restart deploy
  